---
- hosts: localhost
  vars:
    bobs_path: 'azurediamond/password'
    bobs_value: 'hunter2'
  tasks:
    - dcos_secret: path="{{bobs_path}}" state='absent'

    - dcos_secret:
        path: "{{bobs_path}}"
        value: "{{bobs_value}}"
      register: 'dcos_secret'
    - assert: { that: "{{dcos_secret.changed}} == True" }
    - assert: { that: "{{dcos_secret.failed}} == False" }
    - assert: { that: "{{dcos_secret.rc}} == 0" }
    - assert: { that: "{{dcos_secret.status_code}} == 201" }

    - dcos_secret:
        path: "{{bobs_path}}"
      register: 'dcos_secret'
    - assert: { that: "{{dcos_secret.changed}} == False" }
    - assert: { that: "{{dcos_secret.failed}} == False" }
    - assert: { that: "'{{dcos_secret.value}}' == '{{bobs_value}}'" }
    - assert: { that: "{{dcos_secret.rc}} == 0" }
    - assert: { that: "{{dcos_secret.status_code}} == 200" }

    - dcos_secret:
        path: "{{bobs_path}}"
        state: "absent"
      register: 'dcos_secret'
    - assert: { that: "{{dcos_secret.changed}} == True" }
    - assert: { that: "{{dcos_secret.failed}} == False" }
    - assert: { that: "{{dcos_secret.rc}} == 0" }
    - assert: { that: "{{dcos_secret.status_code}} == 204" }

    - dcos_secret:
        path: "{{bobs_path}}"
      failed_when: False
      register: 'dcos_secret'
    - assert: { that: "{{dcos_secret.changed}} == False" }
    - assert: { that: "{{dcos_secret.failed}} == False" }
    - assert: { that: "{{dcos_secret.rc}} == 1" }
    - assert: { that: "{{dcos_secret.status_code}} == 404" }
